// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        //return web;
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoKfRCvKWpVsAXc6Yzd3JveooXrp_hrDA',
    appId: '1:1007609971869:web:644ff8498b36a311664074',
    messagingSenderId: '1007609971869',
    projectId: 'chronote-e7fa5',
    authDomain: 'chronote-e7fa5.firebaseapp.com',
    storageBucket: 'chronote-e7fa5.firebasestorage.app',
    measurementId: 'G-65LMGNES2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRvcdAsclyRd-F4KyGbYga2PRB0VaLaL0',
    appId: '1:1007609971869:android:cd55c684776b94b1664074',
    messagingSenderId: '1007609971869',
    projectId: 'chronote-e7fa5',
    storageBucket: 'chronote-e7fa5.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEAQztostvg0rBvKO0oKUMI7B8GcJu22Y',
    appId: '1:1007609971869:ios:3d5af31b448943aa664074',
    messagingSenderId: '1007609971869',
    projectId: 'chronote-e7fa5',
    storageBucket: 'chronote-e7fa5.firebasestorage.app',
    iosBundleId: 'com.example.eventDiary2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoKfRCvKWpVsAXc6Yzd3JveooXrp_hrDA',
    appId: '1:1007609971869:web:a93e310842c0b822664074',
    messagingSenderId: '1007609971869',
    projectId: 'chronote-e7fa5',
    authDomain: 'chronote-e7fa5.firebaseapp.com',
    storageBucket: 'chronote-e7fa5.firebasestorage.app',
    measurementId: 'G-HYJDBHGMWS',
  );

}